module.exports = tags ={
    '9F21':{
        type:'E',
        description:''
    },
    '9A':{
        type:'E',
        description:''
    },
    '1A04':{
        type:'P',
        description:''
    },
    '1A05':{
        type:'P',
        description:''
    },
    '5F34':{
        type:'E',
        description:''
    },
    '1A07':{
        type:'P',
        description:''
    },
    '1A08':{
        type:'P',
        description:''
    },
    '1B19':{
        type:'P',
        description:''
    },
    '9F03':{
        type:'E',
        description:''
    },
    '1A1B':{
        type:'P',
        description:''
    },
    '1A0A':{
        type:'P',
        description:''
    },
    '1A0B':{
        type:'P',
        description:''
    },
    '1A0C':{
        type:'P',
        description:''
    },
    '4F':{
        type:'E',
        description:''
    },
    '9F26':{
        type:'E',
        description:''
    },

    '9F12':{
        type:'E',
        description:''
    },
    '50':{
        type:'E',
        description:''
    },
    '9F02':{
        type:'E',
        description:''
    },
    '8A':{
        type:'E',
        description:''
    },
    '9C':{
        type:'E',
        description:''
    },
    '1A06':{
        type:'P',
        description:''
    },

    '1A0D':{
        type:'P',
        description:''
    },
    '1A0E':{
        type:'P',
        description:''
    },
    '1A0F':{
        type:'P',
        description:''
    },
    '1A10':{
        type:'P',
        description:''
    },
    '1A11':{
        type:'P',
        description:''
    },
    '1A12':{
        type:'P',
        description:''
    },
    '1A13':{
        type:'P',
        description:''
    },

    '1A14':{
        type:'P',
        description:''
    },
    '9F36':{
        type:'E',
        description:''
    },
    '1A15':{
        type:'P',
        description:''
    },
    '1A16':{
        type:'P',
        description:''
    },
    '1A17':{
        type:'P',
        description:''
    },
    '1A18':{
        type:'P',
        description:''
    },
    '1A19':{
        type:'P',
        description:''
    },
    '1A1A':{
        type:'P',
        description:''
    },
    '1A1C':{
        type:'P',
        description:''
    },
    '1A1D':{
        type:'P',
        description:''
    },
    '1A1E':{
        type:'P',
        description:''
    },
    '1A1F':{
        type:'P',
        description:''
    },
    '1A20':{
        type:'P',
        description:''
    },
    '84':{
        type:'E',
        description:''
    },
    '1B01':{
        type:'P',
        description:''
    },
    '1B02':{
        type:'P',
        description:''
    },
    '1B03':{
        type:'P',
        description:''
    },
    '1B04':{
        type:'P',
        description:''
    },
    '1B08':{
        type:'P',
        description:''
    },
    '9F27':{
        type:'E',
        description:''
    },
    '1B05':{
        type:'P',
        description:''
    },
    '1B06':{
        type:'P',
        description:''
    },
    '1B07':{
        type:'P',
        description:''
    },
    '1B09':{
        type:'P',
        description:''
    },
    '1B10':{
        type:'P',
        description:''
    },
    '1B11':{
        type:'P',
        description:''
    },
    '1B12':{
        type:'P',
        description:''
    },
    '1B1A':{
        type:'P',
        description:''
    },
    '1B1B':{
        type:'P',
        description:''
    },
    '1B1F':{
        type:'P',
        description:''
    },
    '1C04':{
        type:'P',
        description:''
    },
    '1C05':{
        type:'P',
        description:''
    },
    '1C06':{
        type:'P',
        description:''
    },
    '1C07':{
        type:'P',
        description:''
    },
    '1C1A':{
        type:'P',
        description:''
    },
    '1C20':{
        type:'P',
        description:''
    },
    '1C21':{
        type:'P',
        description:''
    },
    '1C22':{
        type:'P',
        description:''
    },
    '1C23':{
        type:'P',
        description:''
    },
    '1C24':{
        type:'P',
        description:''
    },
    '1C25':{
        type:'P',
        description:''
    },
    '1C26':{
        type:'P',
        description:''
    },
    '1C27':{
        type:'P',
        description:''
    },
    '1C28':{
        type:'P',
        description:''
    },


}